### ISSUE TITLE
ignore the auto-format if there is any syntax error

### ISSUE THREAD

**Issue by shaeinst** [mhartington/formatter.nvim#100]
i have enabled auto format on save. Problem is, when there is any syntax error and i save it, it throw big error rows.
for example, i am using yapf for python and it throw me error when there is syntax error and i save it.
![2021-11-13_10-46](https://user-images.githubusercontent.com/41078534/141606317-18842e5c-b950-49aa-aa86-76c5b4ad63ec.png)

**Comment by joao-vitor-sr** [comment]
You can use ```:silent Format```
like @lukas-reineke said in #102
