### ISSUE TITLE
Making formatter work for multifiltypes

### ISSUE THREAD

**Issue by joshpetit** [mhartington/formatter.nvim#101]
Hey! Thanks for this awesome lua plugin. I was wondering if it'd be possible to make this work for files of multiple types. I have a custom filetype that has markdown extensions called "creole.markdown" and in vim if you can use multiple filetypes using the `.` separator. So would it be possible to make the formatter parse this and use one of the defined formatters for one of the filetypes? I would say using the first formatter found in the list of file types would be ideal.

Thank you!

**Comment by mhartington** [comment]
It could potentially be something we could do. A quick work around would be to do something like...


```lua

local baseConfig = function()
  return {
    exe = "exe",
    args = {...},
    stdin = true
  }
end


local markdownVariants = {'markdown', 'creole.markdown'}
for _, ft in ipairs(markdownVariants) do
  formatterConfig[ft] = {baseConfig}
end
```
