### ISSUE TITLE
formatter.nvim should not use "return" as end of function in python

### ISSUE THREAD

**Issue by shaeinst** [mhartington/formatter.nvim#107]
![image](https://user-images.githubusercontent.com/41078534/146765441-9845a5fe-f355-43c2-8062-0a79a3ebb4c9.png)

as you can see in screenshot, formatter.nvim drawing indent line till next function because there is no return in that function.

**Comment by lukas-reineke** [comment]
formatter.nvim does not draw indent lines.
I think you mean https://github.com/lukas-reineke/indent-blankline.nvim?

**Comment by shaeinst** [comment]
i am very sorry. i thought it's indent-blankline.nvim repositories.
