### ISSUE TITLE
Can you help with rustfmt?

### ISSUE THREAD

**Issue by casperstorm** [mhartington/formatter.nvim#11]
Such a great addon, saw it mentioned on Reddit and just set it up with `Prettier`. Super fast.
I am trying to get it to work with `rustfmt` and running into some problems. Might very well be me doing something wrong.

So the way I can format a file in terminal is `rustfmt ./crates/foo/bar.rs --edition 2018`
I have the following setup:

```lua
  rust = {
    rustfmt = function()
      return {
        exe = "rustfmt",
        args = {vim.api.nvim_buf_get_name(0), "--edition 2018"},
        stdin = true
      }
    end
  }
```

When running it I get the error: `E5677: Error writing input to shell-command: EPIPE`.

**UPDATE:** So apparently this works however I guess I run it on all files now.

```lua
  rust = {
    rustfmt = function()
      return {
        exe = "rustfmt",
        args = {"--edition 2018"},
        stdin = true
      }
    end
  }
```

**Comment by mhartington** [comment]
The config should be something like 

```
  rust = {
     rustfmt = function()
      return {
        exe = "rustfmt",
        args = {"--emit=stdout"},
        stdin = true
      }
    end
  }
```

Plus what ever edition you want to use. The key is to make sure to set `--emit` to stdout.
