### ISSUE TITLE
Samples to use prettier and or ESLINT depending on the project settings and configuration

### ISSUE THREAD

**Issue by nbalawat** [mhartington/formatter.nvim#112]
I am not sure what is a good way to configure this great tool to use the configuration provided in the project vs global.  
Example - every project is different and there are differences between them.  Is there a way for the tool to default to local prettier / eslint configurations ( .eslintrc or .eslintrc.js or .prettierc etc).  Also I want to use this tool across the monorepo that might have multiple sub projects with potentially different standards ( striving for consistency...but you know how the world works ).  Would be grateful if you can shed some light.

**Comment by ahmedelgabri** [comment]
For `prettier`, you can do this. Prettier has a `--config-precedence` flag, when set to `prefer-file` it will pick up the local config first & this will take precedence over any global (even CLI flags)

```lua
return {
  exe = 'prettier',
  args = {
    '--config-precedence',
    'prefer-file',
    -- you can add more global setup here 
    '--stdin-filepath',
    vim.fn.shellescape(vim.api.nvim_buf_get_name(0)),
  },
  stdin = true,
}
```

For example, this is my personal setup. Inside a project which has prettier set up, otherwise, it will use my global config (the inline CLI flags)

```lua
return {
  exe = 'prettier',
  args = {
    '--config-precedence',
    'prefer-file',
    '--single-quote',
    '--no-bracket-spacing',
    '--prose-wrap',
    'always',
    '--arrow-parens',
    'always',
    '--trailing-comma',
    'all',
    '--no-semi',
    '--end-of-line',
    'lf',
    '--stdin-filepath',
    vim.fn.shellescape(vim.api.nvim_buf_get_name(0)),
  },
  stdin = true,
}
```

As for `eslint` I don't think it has anything similar.

**Comment by mhartington** [comment]
If you'd be up for making a PR to add to this the config, that would be grea! Thanks @ahmedelgabri

**Comment by ahmedelgabri** [comment]
> If you'd be up for making a PR to add to this the config, that would be great! Thanks, @ahmedelgabri

@mhartington you mean adding the `--config-precedence` flag? This is only useful if you want to have some CLI defaults different than the defaults of `prettier`

**Comment by smithbm2316** [comment]
> For `prettier`, you can do this. Prettier has a `--config-precedence` flag, when set to `prefer-file` it will pick up the local config first & this will take precedence over any global (even CLI flags)
> 
> ```lua
> return {
>   exe = 'prettier',
>   args = {
>     '--config-precedence',
>     'prefer-file',
>     -- you can add more global setup here 
>     '--stdin-filepath',
>     vim.fn.shellescape(vim.api.nvim_buf_get_name(0)),
>   },
>   stdin = true,
> }
> ```

@ahmedelgabri thank you SO much, this is such a simple change to my config that fixes a headache I just started to have on a new project. Exactly what I was looking for! 😄

**Comment by MrLectus** [comment]
>     vim.fn.shellescape(vim.api.nvim_buf_get_name(0)),

Please what does this do?

**Comment by ahmedelgabri** [comment]
> >     vim.fn.shellescape(vim.api.nvim_buf_get_name(0)),
> 
> 
> 
> Please what does this do?

Makes sure that escapes any values in the file name which might need to be escaped in a shell environment. 

`:help shellescape` for more info.
