### ISSUE TITLE
Get rid of file changed warning? 

### ISSUE THREAD

**Issue by karlc1** [mhartington/formatter.nvim#113]
When using this plugin, I get a lot of these warnigs, when using an autocmd to format on save: 

```
WARNING: The file has been changed since reading it!!!
Do you really want to write to it (y/n)?
``` 

Before, I used a custom autocmd to format golang on save, and never saw this. Any advice on how to get rid of this?

**Comment by lukas-reineke** [comment]
That is not an error message of this plugin.
You are probably using something else that also tries to format on save, and then gives this error message?
