### ISSUE TITLE
is it possible to run multiple formatters for a filetype?

### ISSUE THREAD

**Issue by xsteadfastx** [mhartington/formatter.nvim#117]
i think about moving from format.nvim to this. but i have a few filetypes that needs multiple formatters. like go... i need goimports and gofumpt. in format.nvim it is

```
                        go = {
                            {
                                cmd = {"goimports -w", "gofumpt -w"},
                                tempfile_postfix = ".tmp"
                            }
                        },
```

or in yaml i need also kustomize

```
                        yaml = {
                            {cmd = {"prettier -w", "kustomize cfg fmt"}}
                        },

```

**Comment by mhartington** [comment]
You can run multiple formatters, you just create a new entry in the same filetype table.


```
 go = {
  -- goimports
  function()
    return {
      exe = "goimports",
      args = {...}
    }
  end,
  -- gofumpt
  function()
    return {
      exe = "gofmpt",
      args = {...}
    }
  end
}
```

**Comment by xsteadfastx** [comment]
i really dont get it work. my config looks like this:

https://gist.github.com/xsteadfastx/a87706f22285506fb07f62e96af74701#file-init-lua-L261

goimports just wont work. it doesn nothing. any idea how to debug?

**Comment by lukas-reineke** [comment]
You are using `args = {"-w"}` and `stdin = true`. That contradicts itself.
remove the args and it should work

**Comment by xsteadfastx** [comment]
i used this from the examples: https://github.com/mhartington/formatter.nvim/blob/master/CONFIG.md#golang

also lua-fmt... copied from examples... it does nothing. is there a debug more or something?

**Comment by xsteadfastx** [comment]
also updated config: https://gist.github.com/xsteadfastx/e39facac21454d57c317c34e3894b827#file-init-lua-L262

**Comment by xsteadfastx** [comment]
i missed the filetype = {}...oh sorry :)
