### ISSUE TITLE
Configure Formatter.nvim & Latexindent

### ISSUE THREAD

**Issue by flaviusbuffon** [mhartington/formatter.nvim#124]
I try config given by author 👍🏼:
```require("formatter").setup({
	filetype = {
		tex = {
			function()
				return {
					exe = "latexindent",
					args = { "-" },
					stdin = true,
				}
			end,
		},
	},
})`
,
but it failed to format.

* neovim v0.7.0-dev+1160-g01139ec82c
* packer

**Comment by lukas-reineke** [comment]
your config looks correct.
What happens when you run `cat file.tex | latexindent -` on the comand line?

**Comment by flaviusbuffon** [comment]
Successfully excute and output right format of the tex file.
That is why i feel amuse for that.

**Comment by lukas-reineke** [comment]
can you check if the filetype is set correctly? `:set filetype`
