### ISSUE TITLE
Why FormatWrite III in my code file?

### ISSUE THREAD

**Issue by sober-wang** [mhartington/formatter.nvim#132]
![image](https://user-images.githubusercontent.com/35804630/162703365-ae5a7462-f465-45bd-b7c4-e296f153b1ad.png)

my formatter config 
```lua
    go = {
      function()
        return {
          exe = "gofmt",
          --args = {
          --  "-w",
          --  vim.fn.fnameescape(vim.api.nvim_buf_get_name(0)),
          --},
          stdin = true,
        }
      end,
    },
```

<img width="761" alt="image" src="https://user-images.githubusercontent.com/35804630/162704005-51e990da-de5e-446d-8720-871eee508b88.png">

**Comment by lukas-reineke** [comment]
> the tab is displayed as ^I in vim

Correct :+1: . You can also change how it is displayed with `:help listchars`
