### ISSUE TITLE
neovim informs the file has been changed after reading it when using `stdin = false`

### ISSUE THREAD

**Issue by insidewhy** [mhartington/formatter.nvim#141]
Getting this after every write with a formatting change:

```
WARNING: The file has been changed since reading it!!!                                                          
Do you really want to write to it (y/n)?  
```

Then have to click `y` then `return` which gets kind of annoying. It happens for formatters that use `stdin = false`.

Here's an example config with dart:

```lua
local function format_dart()
  return {
    exe = "/opt/flutter/bin/dart",
    args = { "format", vim.api.nvim_buf_get_name(0) },
    stdin = false,
    ignore_exitcode = true,
  }
end

require('formatter').setup {
  logging = true,
  filetype = {
    dart = { format_dart },
  }
}
vim.api.nvim_exec([[
augroup FormatAutogroup
  autocmd!
  autocmd BufWritePost *.dart FormatWrite
augroup END
]], true)
```

**Comment by lukas-reineke** [comment]
don't pass `vim.api.nvim_buf_get_name(0)` as an argument.

**Comment by insidewhy** [comment]
Ah thanks that works, the former used to work.

**Comment by karma-riuk** [comment]
> don't pass vim.api.nvim_buf_get_name(0) as an argument.

This solution worked for me as well (with another formatter), but could you explain the reason behind it? I'm curious to know :)

**Comment by lukas-reineke** [comment]
`stdin=false` works by creating a temporary file, formatting that, and then writing the changes back into the buffer.
It basically runs `{exe} {args} {tempfile}`.

Now, if you pass the actual filename as an argument, this turns into `{exe} {args} {file} {tempfile}`.
So the formatter will format the original file directly, outside of Neovim. And you get the `The file has been changed since reading it!!!` warning.

**Comment by Tauromachian** [comment]
I am having a similar problem and I am not adding the file name to the args. This happens with my configuration for Laravel Pint. 
My configs:

```lua
local function php()

    return {
        exe = "./vendor/bin/pint",
        stdin = false,
        no_append = true
    }
end

require('formatter').setup {
    filetype = {
        php = { php }
    }
}

vim.api.nvim_exec([[
augroup FormatAutogroup
  autocmd!
  autocmd BufWritePost *.php FormatWrite
augroup END
]], true)
```
This configs work but it's an awful experience. It keeps prompting me about the the changes in the file.

Am I doing something wrong with my configs?
