### ISSUE TITLE
Formatter events are being suppressed

### ISSUE THREAD

**Issue by scienceplease** [mhartington/formatter.nvim#143]
When defining autocommands for events (e.g. `FormatterPost`), they are never triggered on `:Format`. I'm only able to catch `FormatterPost` when the `silent` option below is removed.  

https://github.com/mhartington/formatter.nvim/blob/b7b307d637b22ae0266c60309a016fb325a4d6e5/lua/formatter/util.lua#L129

**Comment by Hrle97** [comment]
@scienceplease Can you post an example of the `autocmd`?

**Comment by scienceplease** [comment]
@Hrle97 sure thing. Here is an example of an `autocmd` I was able to formulate to capture the appropriate event, only after removing `silent`. I had to resort to using `pattern`.

```lua
local augroup = vim.api.nvim_create_augroup
local autocmd = vim.api.nvim_create_autocmd

local UserPyright = augroup('UserPyright', { clear = true })

autocmd('User', {
    desc = 'Organize imports with Pyright after formatting.',
    group = UserPyright,
    pattern = 'FormatterPost',
    callback = function(opts)
        vim.cmd([[PyrightOrganizeImports]])
    end,
})


```

**Comment by Hrle97** [comment]
Reading the docs:
```
:do[autocmd] [<nomodeline>] [group] {event} [fname]

When the [group] argument is not given, Vim executes                                                                                                                
the autocommands for all groups.  When the [group]                                                                                                                  
argument is included, Vim executes only the matching                                                                                             
autocommands for that group.  Undefined group is an
error. 
```

Seems like the group argument there is `User` and the event is `FormatterPost`. Can you try putting the `autocmd` in the `User` `augroup` and setting the event for the autocmd to `FormatterPost` without the pattern option?

I'm not exactly sure why it is like that - I'm just trying to help for now.

**Comment by scienceplease** [comment]
I get the following error from `nvim_create_autocmd` stating `"unexpected event"` (stack trace omitted).

```lua
local augroup = vim.api.nvim_create_augroup                                                                            
local autocmd = vim.api.nvim_create_autocmd                                                                            
                                                                                                                       
local User = augroup('User', { clear = false })                                                                        
                                                                                                                       
autocmd('FormatterPost', {                                                                                             
    desc = 'Testing our formatter events.',                                                          
    group = User,                                                                                                      
    callback = function(opts)                                                                                          
        print('test')                                                                                                  
    end,                                                                                                               
}) 
```

```
Error executing vim.schedule lua callback: ...an/.config/nvim/lua/user/plugins/lsp/servers/pyright.lua:108: unexp
ected event
```

Poking around, I see that `User` is documented as one of the **events** that nvim recognizes, not a group (`:h User`). Upon further reading (`:h autocmd-events`) it doesn't appear possible to define events beyond this list, as `User` is a catch-all for custom events. Easiest way to see this in action is to run the below. Note that you still need to remove `silent` from the `doautocmd` invocation as I mentioned before.

```lua
local augroup = vim.api.nvim_create_augroup                                                                            
local autocmd = vim.api.nvim_create_autocmd                                                                            
                                                                                                                       
local Debug = augroup('Debug', { clear = true })                                                                       
                                                                                                                       
autocmd('User', {                                                                                                      
    group = Debug,                                                                                                      
    pattern = 'Formatter*',                                                                                            
    callback = function(opts)                                                                                          
        print(vim.inspect(opts))                                                                                       
    end,                                                                                                               
})
```

Output after calling `:Format`:
```
{
  buf = 1,
  event = "User",
  file = "FormatterPre",
  id = 28,
  match = "FormatterPre"
}
{
  buf = 1,
  event = "User",
  file = "FormatterPost",
  id = 28,
  match = "FormatterPost"
}
```

**Comment by Hrle97** [comment]
Sorry, my bad. It seems I misinterpreted that documentation.

I still don't understand why `silent` has any impact on this,  so I am still hesitant to just remove `silent` there. Isn't `silent` just a command that makes error messages of other commands go away? I read the documentation on it now to refresh my memory and I don't see anything that would make it not fire an event if used on `doautocmd`.

From my POV, this seems like an issue with Neovim, but I'll try reproducing this on my end tomorrow and maybe I find out something more about this.

**Comment by scienceplease** [comment]
Ah, of course! Can't believe I didn't make that connection, thank you.

I updated the debug example above to log to a file in your home directory as `Formatter` events are caught. You can just `tail -f ~/formatter-debug.log` and not bother with my Pyright configuration.

**Comment by Hrle97** [comment]
Thank you for the update and it seems everything works as it should on my end, meaning that I can see entries in `~/formatter-debug.log` with the `silent` argument. If everything is okay on your end, I would like to create a feature that disables `silent` when the log level is greater or equal to `debug` and close this issue if that is okay with you.

**Comment by Hrle97** [comment]
Not closing this until @scienceplease gives me a green light.

**Comment by scienceplease** [comment]
Yup, everything is working on my end! Go ahead and close it
