### ISSUE TITLE
If exe is not found there aren't any errors

### ISSUE THREAD

**Issue by Mte90** [mhartington/formatter.nvim#151]
So I am trying to get my config for phpcbf working.
I saw that if the tool is not available in the path there aren't any errors also the tool doesn't offer any commands for debug, like to see the configuration inside neovim (ALE as I can remember have that).

In the meantime I am trying to enable the debug to see what is happening but the documentation doesn't mention it.

**Comment by Mte90** [comment]
So the error is a warning but is not printed if that debug mode is not enabled (I disabled the check to get all the errors).

**Comment by mhartington** [comment]
So logging is enabled to basically keep things quiet as much as possible. It looks like the logging information didn't make it over to the new vim docs, but you should enable loggin via 

```
  require("formatter").setup {
  logging = true,
  log_level = 2
}
```

I'll get that added to the docs.
