### ISSUE TITLE
[Feature request] format markdown fenced code

### ISSUE THREAD

**Issue by devkvlt** [mhartington/formatter.nvim#162]
Currently, this only works with languages that use the same formatter as the markdown.

**Comment by cmdcolin** [comment]
note that prettier can do this to some extent out of the box for languages that prettier itself supports

see

```
% cat test.md
hello


```javascript
function world() {
console.log('hi')
}
```

~
% npx prettier test.md
hello

```javascript
function world() {
  console.log("hi");
}
```

so, if you have prettier+formatter.nvim, it could handle some cases at least

**Comment by Hrle97** [comment]
Closing in favor of #176 since treesitter is the way to go nowadays in terms of filetype detection in code blocks.
