### ISSUE TITLE
Can't get reorder-python-imports to work

### ISSUE THREAD

**Issue by denismaciel** [mhartington/formatter.nvim#178]
I am trying to set up [reorder-python-imports](https://pypi.org/project/reorder-python-imports/) with formatter.nvim, but I am unable to get it to work.

This is how I am configuring it:

```lua
require("formatter").setup({
	logging = true,
	log_level = vim.log.levels.DEBUG,
	filetype = {
		python = {
			function()
				return {
					exe = "reorder-python-imports",
					args = { "-" },
					stdin = true,
				}
			end,
		},
	},
})
```

From the CLI, reorder-python-imports works fine:

```
$ echo "import os, sys" > t.py
$ cat t.py | reorder-python-imports -
import os
import sys
```

But from neovim, I am getting `No change necessary with reorder-python-imports`. Am I missing something here?

**Comment by Hrle97** [comment]
I don't think you're missing something here. It looks like a bug. I'll check it out in the next couple of days. Is [this](https://pypi.org/project/reorder-python-imports/) the package you're using?

**Comment by Hrle97** [comment]
Can you try this @denismaciel :
```lua
require("formatter").setup({
	logging = true,
	log_level = vim.log.levels.DEBUG,
	filetype = {
		python = {
			function()
				return {
					exe = "reorder-python-imports",
					args = { "-" },
					stdin = true,
                                        ignore_exitcode = true,
				}
			end,
		},
	},
})
```
Note the `ignore_exitcode` property.

**Comment by denismaciel** [comment]
That solve my issue, @Hrle97. Thank you!

About having an issue template with "things you could try", yes, it would definitely be helpful!
