### ISSUE TITLE
[Feature] Fallback to LSP formatting if no formatter is configured

### ISSUE THREAD

**Issue by nullishamy** [mhartington/formatter.nvim#192]
Love the project! Just one suggestion:

It would be nice to have an option, in some form, to fall back to LSP formatting if a formatter is not configured. Some languages do not have external formatters (or what does exist is subpar), and in other cases it is simply too much effort to install one for a small snippet.

Given the design of the project, a default `all` formatter would likely be the solution here.

**Comment by coffebar** [comment]
@nullishamy 
You use [this](https://github.com/coffebar/dotfiles/blob/398947ea257c2579dd83b605e2b47fd4af6e5634/.config/nvim/after/plugin/lspconfig.lua#L29,L39) in your config for lsp. 

If lsp can't handle formatting - it will be mapped to ':Format<cr>'

If you want to force using Format for particular file format, you can disable formatting capabilities in LSP

**Comment by tjex** [comment]
Sorry to spark up a seriously old issue, but I'm not sure the proposed config really works? At least not on my end. 

It would seem the client advertises formatting abilities as a base capability. 
Then the settings (to disable a certain lsp's formatter) are loaded for that client.

But as far as the `on_attach` is concerned, the client *does* have formatting capabilities (as they are disabled after they have been advertised to `on_attach`, and will then never reach the else branch to set the keymap to be used for `:Format`?

**Comment by coffebar** [comment]
@tjex
try [this](https://github.com/coffebar/dotfiles/blob/c4fe571af44ba4922b9b41ed009e6c8ea6508ab0/.config/nvim/after/plugin/lspconfig.lua#L54)
I have listed lsp client names to use with Formatter

**Comment by tjex** [comment]
yeah nice :) I just came on here with the same, but less clean solution:

```lua
local lsp_attach = function(client, bufnr)
	local bufopts = { noremap = true, silent = true, buffer = bufnr }
	if client.name == "tsserver" or "lua_ls" then
		client.server_capabilities.document_formatting = false
	end
	lsp_keymaps(client, bufnr)
	require("cmp_nvim_lsp").default_capabilities()
	if client.server_capabilities.document_formatting then
		vim.keymap.set({ "v", "n" }, "<leader>f", vim.lsp.buf.format, bufopts)
	else
		vim.keymap.set("n", "<leader>f", ":Format<cr>", bufopts)
	end
	-- client.server_capabilities.document_formatting = true
	-- disable lsp semantic highlighting. It flashes...
	client.server_capabilities.semanticTokensProvider = nil
end
```

Thanks all the same!

**Comment by tjex** [comment]
Because I wasn't actually sure that `client.server_capabilities.documentFormattingProvider` was still a part of the API. 
Nothing came up in my completion and couldn't get it to return any boolean to print... But if it's working for you, then I'm (once again) a bit in the blue!

**Comment by coffebar** [comment]
Just checked: `server_capabilities.documentFormattingProvider` is present in some LSP clients, it's not deprecated. 

However, I found for myself to have a hardcoded list of clients will be as reliable as possible.

**Comment by tjex** [comment]
> @tjex
> try [this](https://github.com/coffebar/dotfiles/blob/c4fe571af44ba4922b9b41ed009e6c8ea6508ab0/.config/nvim/after/plugin/lspconfig.lua#L54)
> I have listed lsp client names to use with Formatter

my approach was buggy / incorrect. use coffebars 👆

**Comment by borisboskovic** [comment]
I can get available formatters and format with LSP if there are none

```lua
local prettierd_formatter = {
    function()
        return {
            exe = "prettierd",
            args = { vim.api.nvim_buf_get_name(0) },
            stdin = true
        }
    end
}

require('formatter').setup({
    logging = false,
    filetype = {
        javascript = prettierd_formatter,
        typescript = prettierd_formatter,

        -- Format with LSP if there are not other formatters
        ["*"] = {
            function()
                local formatters = require("formatter.util")
                    .get_available_formatters_for_ft(vim.bo.filetype)
                local formatters_len = 0
                for _ in pairs(formatters) do
                    formatters_len = formatters_len + 1
                end
                if formatters_len == 0 then
                    print("Formatted with LSP")
                    vim.lsp.buf.format()
                end
            end
        }
    }
})
```
