### ISSUE TITLE
Consider changing the way formatter.nvim is configured

### ISSUE THREAD

**Issue by Diablo-D3** [mhartington/formatter.nvim#193]
[nvim-lint](https://github.com/mfussenegger/nvim-lint) uses this for its Lua configuration:

```
require('lint').linters_by_ft = {
  markdown = {'vale',}
}
```

Being able to very quickly specify the configuration like this would be very useful, and probably increase the adoption rate.

**Comment by mhartington** [comment]
This probably is not going to happen, as it would be a massive breaking change (one that I don't think would be super beneficial). The current config setup is the way it is to support the various ways formatters can be setup.
