### ISSUE TITLE
E5108: Error executing lua [string ":lua"]:1: attempt to call field 'format' (a nil value)

### ISSUE THREAD

**Issue by luozhiya** [mhartington/formatter.nvim#198]
Hi,

Using the default configuration, and try to format lua file, neovim throw:
E5108: Error executing lua [string ":lua"]:1: attempt to call field 'format' (a nil value)
stack traceback:
        [string ":lua"]:1: in main chunk

Thanks

**Comment by Hrle97** [comment]
sorry for the wait

please post your config, the file in question and a screenshot of this happening if you can

**Comment by luozhiya** [comment]
@Hrle97 The problem that I cannot reproduce now, may be fixed by updating to the latest version.
