### ISSUE TITLE
Format.lua: Exepected lua table

### ISSUE THREAD

**Issue by AkalUstat** [mhartington/formatter.nvim#20]
Hi, I am new to this plugin and lua, so sorry if this is a simple/stupid question.
I have defined by setup like this:
```ua
require('formatter').setup({
  logging = false,
  filetype = {
    typescriptreact = {
        -- prettier
       function()
          return {
            exe = "prettier-eslint",
            args = {"--stdin-filepath", vim.api.nvim_buf_get_name(0) },
            stdin = true
          }
        end
    },
  }
})
```

Whenever I run `:Format`, I get this error: `Expected lua table function: builtin#18...ack/packer/start/formatter.nvim/formatter/format.lua:117: Expected lua table`.

Can you guide me in the right direction for fixing this/understanding this?

Thank you

**Comment by mhartington** [comment]
This looks fine for setup, do you have a more complete rc file or better yet, your dotfiles up on github that I could look at? f

**Comment by AkalUstat** [comment]
yea here is my dotfiles repo: https://github.com/AkalUstat/dotfiles
the formatting config is in here: https://github.com/AkalUstat/dotfiles/tree/main/.config/nvim/lua/lsp

**Comment by mhartington** [comment]
You're just missing the `--stdin` flag in the args table.

```
  typescriptreact = {
        -- prettier
       function()
          return {
            exe = "prettier-eslint",
            args = {"--stdin", "--stdin-filepath", vim.api.nvim_buf_get_name(0) },
            stdin = true
          }
        end
    },
```

https://github.com/prettier/prettier-eslint-cli#cli-options


Might be a bit confusing, but the `stdin` of the formatter.nvim table is meant to change how the command is run/processed. You still need to provide the `--stdin` flag to the exe args if it is needed.

**Comment by AkalUstat** [comment]
oh thats why...Thanks so much for helping (even if it wasnt a plugin issue :) )
