### ISSUE TITLE
`sed: illegal option --` on MacOS

### ISSUE THREAD

**Issue by ananthb** [mhartington/formatter.nvim#201]
Shell command and output (optional):

```shell
> sed --in-place
sed: illegal option -- -
usage: sed script [-Ealnru] [-i extension] [file ...]
        sed [-Ealnu] [-i extension] [-e script] ... [-f script_file] ... [file ...]
```

**Which configuration?**
Type (custom or builtin):
Filetype: *
Formatter: defaults.sed (removes trailing whitespace)

Configuration(s) (post all the variants you tried):
```lua
-- ...      
    require('formatter').setup {
        filetype = {
          ['*'] = {
            require('formatter.filetypes.any').remove_trailing_whitespace
          }
        }
      }
-- ...
```

**Expected behavior**
sed removes trailing whitespace.

**Actual behaviour**
sed doesn't understand `--` flags on MacOS.

**Additional context**
If the sed executable's path was configurable, we could install GNU sed on MacOS using homebrew, etc, and use gsed instead.

**Comment by Hrle97** [comment]
sry for the wait

ill add detection for `macos` using `vim.fn.has` for that config

**Comment by benjamineskola** [comment]
I think instead of `--in-place` you'd want to use `-i ''`.

I _believe_ that would also work with GNU sed, but I haven't tested that.
