### ISSUE TITLE
Elixir: heex not supported?

### ISSUE THREAD

**Issue by seghers** [mhartington/formatter.nvim#206]
Running :FormatWrite works for `.ex` & `.exs`, but `.html.heex` doesn't work.

It works when I run `mix format` outside nvim, in my terminal.

.formatter.exs:
``` elixir
[
  import_deps: [:ecto, :phoenix],
  plugins: [Phoenix.LiveView.HTMLFormatter],
  inputs: ["*.{heex,ex,exs}", "priv/*/seeds.exs", "{config,lib,test}/**/*.{heex,ex,exs}"],
  subdirectories: ["priv/*/migrations"]
]
```

**Comment by Hrle97** [comment]
hmm maybe the filetype doesnt get picked up or its a different one

please post your config, the file in question, its filetype and a screenshot if you can
