### ISSUE TITLE
Option to autoformat in all supported filetypes

### ISSUE THREAD

**Issue by lucastrvsn** [mhartington/formatter.nvim#21]
Hello! I'm using this plugin for a time and it's awesome! But I think would be nice to provide a option to autoformat for all the supported filetypes in the setup process. I can do this by autocmds, but it'll be nice if we can just turn a setting on and off. (maybe provide some default config to create a autocmd in the docs?)

Thanks for all work!

**Comment by mhartington** [comment]
Not sure I understand what you are asking for here.

**Comment by lucastrvsn** [comment]
> Not sure I understand what you are asking for here.

Sorry, I'll try to explain a little more.

When doing the setup process, maybe include a option to enable autoformat on save, on write and so on. Like, I have this config:

```lua
local prettier = function()
  return {
    exe = "prettier",
    args = {"--stdin-filepath", vim.api.nvim_buf_get_name(0), '--single-quote'},
    stdin = true
  }
end

local rustfmt = function()
  return {
    exe = "rustfmt",
    args = {"--emit=stdout"},
    stdin = true
  }
end

require('formatter').setup({
  logging = false,
  filetype = {
    javascript = {
      prettier
    },
    javascriptreact = {
      prettier
    },
    typescript = {
      prettier
    },
    typescriptreact = {
      prettier
    },
    rust = {
      rustfmt
    }
  }
})
```
My proposal is to add some option to enable autoformat on save like this:

```lua
...
    javascript = {
      format_on_save = true, -- or run_on_save idk
      runner = prettier
    },
    javascriptreact = {
      format_on_save = false,
      runner = prettier
    },
...
```

If think this way will be more clean solution than add alot of autocmds on our config file to do this. I don't know if you get me, let me know. Thanks!

**Comment by lukas-reineke** [comment]
That option would be very opinionated. It would work fine for some and break for others.
We can't know what else the user might want to do on save, and in which order.

And you only need this simple autogroup in your config currently.
That is a lot more flexible.

```vim
augroup FormatAutogroup
    autocmd!
    autocmd BufWritePost * FormatWrite
augroup END
```

**Comment by lucastrvsn** [comment]
No problem, I get your point. Going to use autocmds for that.

Maybe is a great opportunity to add this snippet to readme? Thanks a lot!

**Comment by lukas-reineke** [comment]
> Maybe is a great opportunity to add this snippet to readme (didn't know FormatWrite exists)? Thanks a lot!

agreed, documentation could be a lot better. Vim docs would also be nice.
Not sure if @mhartington has planned on writing this, I would be willing to do that after my 2 PRs are done and merged.

**Comment by lucastrvsn** [comment]
When I get home I can help creating some docs and examples. Let me know, thanks everyone!

**Comment by maisiliym** [comment]
The idea still has merit given that `nvim_buf_set_text` is now merged; it is now possible to implement a proper async formatter, which was discussed on [reddit](https://www.reddit.com/r/neovim/comments/jvisg5/lets_talk_formatting_again/)

**Comment by lukas-reineke** [comment]
Yes, there is an issue open for `nvim_buf_set_text` #22 
But that doesn't change the fact that adding opinionated options like `format_on_save` is not a good idea.

**Comment by maisiliym** [comment]
> `format_on_save` is not a good idea.

A better idea would be `(auto)format_triggers`, which would take autocmd trigger list as argument.

**Comment by mhartington** [comment]
Im going to agree with @lukas-reineke here. General idea is that less is more.
