### ISSUE TITLE
Expose Lua API

### ISSUE THREAD

**Issue by aspeddro** [mhartington/formatter.nvim#211]
Following a practice in most plugins:

1. Expose the Lua API and its documentation
2. ~~Remove the commands plugin `Format`, `FormatWrite`...~~
3. Let the user create their commands

**Comment by Hrle97** [comment]
I don't know whate is there to expose really.
Removing the commands would break a lot of users configs.
Users are always welcome to create their own commands.

**Comment by aspeddro** [comment]
What I say is to have a lua function documented to format.

Example: `lua require("formatter.format").format()` raise a error.

```
E5108: Error executing lua ...ack/packer/start/formatter.nvim/lua/formatter/format.lua:20: attempt to perf
orm arithmetic on local 'start_line' (a nil value)
stack traceback:
        ...ack/packer/start/formatter.nvim/lua/formatter/format.lua:20: in function 'format'
        [string ":lua"]:1: in main chunk
```

**Comment by Hrle97** [comment]
Yeah there is already an issue to improve documentation but I wasn't able to get around to doing it.

I'll link this issue over there so I know what else needs to be documented.

**Comment by mhartington** [comment]
Just curious, why? You don't really get anything better by exposing those APIs. The commands just simplify the arguments needed for internal APIs.

**Comment by aspeddro** [comment]
Users are configuring using lua, because it's easier, so yes, it's an improvement. For example pass the format function as a callback. 

Note: I removed the second point because it break a lot of users configs.

**Comment by calops** [comment]
I second this. I think it's more idiomatic in a lua configuration to call something like `require("formatter").format_write()` instead of `vim.cmd("FormatWrite")`. It also plays better with how `lazy.nvim` (for example) handles lazy loading without requiring the user to specify an exhaustive list of commands (which can change).

**Comment by mhartington** [comment]
Closing this as I don't think I'll be adding it. Moving from commands to functions doesn't gain anything in my opinion, it just moves the burden of passing the right options on to users, when vim commands handle this automatically.

**Comment by calops** [comment]
It's fair if you don't want to implement this, but this suggestion wouldn't replace the commands, just expose them to lua directly. The burden stays the same no matter which version you use.

My point about lazy loading is a big enough difference to make it worthwhile, in my opinion.
