### ISSUE TITLE
[Feature] calculate diff to preserve `extmarks`, ... with `nvim_buf_set_text`

### ISSUE THREAD

**Issue by lukas-reineke** [mhartington/formatter.nvim#22]
as `nvim_buf_set_text` was merged, we should switch to using that.
It updates the buffer text without changing extmarks

https://github.com/neovim/neovim/pull/11833

**Comment by mhartington** [comment]
Yeah, I saw that. I'm looking at what would be the best way to make use of it,  mainly getting the cols needed for it.

**Comment by atomdmac** [comment]
👋 Is this change still under consideration?

**Comment by lukas-reineke** [comment]
To make this actually useful, formatter.nvim would need to calculate the diff between the old and new state of the buffer.
We talked about this already in #73 and #76 

IMO it is a necessary feature, a lot of stuff breaks without it. (jumps, changes, marks, folds, etc etc)
That's one of the main reasons I built diff into EFM and use that instead.

But it is not trivial to do, so I'm not sure anyone will implement this for formatter.nvim

**Comment by atomdmac** [comment]
Thanks, @lukas-reineke - did you need to modify EFM to get this functionality or is it part of your config for EFM?

**Comment by atomdmac** [comment]
Thanks, @lukas-reineke - did you need to modify EFM to get this functionality or is it part of your config for EFM?

**Comment by lukas-reineke** [comment]
I contributed it directly to EFM. It's built in now, no need to do anything special.

**Comment by Mephistophiles** [comment]
> To make this actually useful, formatter.nvim would need to calculate the diff between the old and new state of the buffer.

nvim has a `vim.diff` function, but it only works with line numbers (no columns) and requires a string instead of a table of strings as in the current implementation. This makes finding fragments in the new (`output`) buffer difficult.

**Comment by atomdmac** [comment]
@lukas-reineke Thanks for the suggestion.  I spent some time switching over to `efm` today and it's working nicely.

**Comment by Hrle97** [comment]
Can we close this in favor of #176? It seems like having treesitter powered formatting would solve this as well.

**Comment by lukas-reineke** [comment]
> It seems like having treesitter powered formatting would solve this as well.

It does not. This is a different problem.
This ticket is about not overwriting sections of the buffer that did not change to preserve ext marks

**Comment by Hrle97** [comment]
Ok my bad! I edited the title, so its a bit more clear what this would do. I know some things about `neovim`, but I have so much to learn, so thank you for the correction.

**Comment by FelipeLema** [comment]
sounds like using `mkview` / `loadview` might be enough (see https://github.com/sbdchd/neoformat/issues/59#issuecomment-698494228 )

**Comment by lukas-reineke** [comment]
mkview does not save extmarks

**Comment by FelipeLema** [comment]
oh, so `mkview` / `loadview` only cover the folds, then 🤔

**Comment by mhartington** [comment]
Reviving this. I have taken a look at how this can happen, reviewed how plugins, like conform, handle this and have a working branch `diff-view`
