### ISSUE TITLE
Enable formatter for explicit use only

### ISSUE THREAD

**Issue by MoritzBoehme** [mhartington/formatter.nvim#229]
Hey, I was wondering if there is a possibility to enable a formatter for explicit use only.
For example if I want to format a nix file I want to use nixpkgs-fmt as the default, but only sometimes I want to use alejandra (not always, as it is more opinionated than the default formatter).
In the cases where I want to use the non default formatter, my ideal usage would just be to call `:Format alejandra`. When calling `:Format` on a nix file it would ideally ignore alejandra, because I didn't explicitly choose it.
Is this or something alike possible?
Could I perhaps wrap the default config for alejandra to detect if it was called explicitly?

**Comment by akanmuratcimen** [comment]
You can use something like this: 
```lua
vim.api.nvim_create_user_command("Fmt", function(opts)
  local params = vim.split(opts.args, "%s+", { trimempty = true })
  vim.cmd("set filetype=".. params[1] .." | :Format")
end, { bang = true, nargs = "?" })
```
example usage: `:Fmt json`

**Comment by MoritzBoehme** [comment]
This is really cool, but I don't think it allows to configure multiple formatters for one language (in my case nix) and not use all of them by default.
Sorry if this is a bit repetitive, however I don't really know how else to describe it.

**Comment by MoritzBoehme** [comment]
Great, this works well enough.
For anyone wanting to replicate this:
```lua
require("formatter").setup({
  filetype = {
    -- HACK to use specific formatters only when specified
    alejandra = {
      require("formatter.filetypes.nix").alejandra,
    },
  },
})

vim.api.nvim_create_user_command("Fmt", function(opts)
  local params = vim.split(opts.args, "%s+", { trimempty = true })
  local filetype = vim.bo.filetype
  vim.cmd("set filetype=" .. params[1]) -- fake filetype
  vim.cmd(":Format")
  vim.cmd("set filetype=" .. filetype) -- restore original filetype
end, {
  nargs = 1,
  complete = function()
    local languages = {
      nix = { "alejandra" },
    }
    return languages[vim.bo.filetype] or {}
  end,
})
```

**Comment by akanmuratcimen** [comment]
Thanks for sharing your solution.

**Comment by MoritzBoehme** [comment]
Considering this works well enough for me, I think this issue is closed.
