### ISSUE TITLE
Clang-format style file ignored

### ISSUE THREAD

**Issue by thilofischer** [mhartington/formatter.nvim#235]
**Which configuration?**
Type (custom or builtin): default clang-format
Filetype: .cpp
Formatter: clang-format

**Expected behavior**

A .clang-format style file is used to specify the desired code style.

**Actual behaviour**

A default style is used.

**Additional context**
This seems to be caused by this [line](https://github.com/mhartington/formatter.nvim/blob/ed949c13e1a942db29ababa35e8c7864ced90eb6/lua/formatter/defaults/clangformat.lua#L7)
As the `-style` flag is passed, the `.clang-format` file is ignored. Removing the line fixed the issue for me.

**Comment by mediumrarez** [comment]
A temporary monkey-patch until this is fixed.

```lua
local patch_clangformat_bug = function(f)
  local o = f()
  if o.args and type(o.args) == 'table' then
    local new_args = {}
    local skip = false
    for i, v in ipairs(o.args) do
      if skip then
        skip = false
      elseif v == '-assume-filename'
        and (o.args[i + 1] == "''" or o.args[i + 1] == '""')
      then
        skip = true
      elseif type(v) ~= 'string' or not v:find('^-style=') then
        table.insert(new_args, v)
      end
    end
    o.args = new_args
  end
  return o
end

require("formatter").setup({
  filetype = {
    cpp = { patch_clangformat_bug(require('formatter.filetypes.cpp').clangformat) }
  }
})
```

**Comment by aritroCoder** [comment]
How do we specify the formatting in args if we need it?

**Comment by eriol** [comment]
I think this can be closed since it was fixed by https://github.com/mhartington/formatter.nvim/pull/236.

I just tested it in a project: the defined `.clang-format` is correctly used.
