### ISSUE TITLE
Expected lua table

### ISSUE THREAD

**Issue by p00f** [mhartington/formatter.nvim#24]
config:
```lua
require('formatter').setup({
  logging = false,
  filetype = {
    cpp = {
       function()
          return {
            exe = "clang-format",
            args = {"-i", "--style=Google"},
            stdin = true
          }
        end
    },
    lua = {
        -- luafmt
        function()
          return {
            exe = "luafmt",
            args = {"--indent-count", 2, "--stdin"},
            stdin = true
          }
        end
      }
  }
})
```
Formatting lua works fine, but running `:Format` on cpp gives `.../packer/start/formatter.nvim/lua/formatter/format.lua:117: Expected lua table`

**Comment by p00f** [comment]
I tried putting lua first and cpp second too

**Comment by lukas-reineke** [comment]
`clang-format` doesn't set the correct exit code.

It errors with `error: cannot use -i when reading from stdin.`, but sets the exit code to 0, so `formatter.nvim` thinks it executed correctly.
Not much we can do about that.

But to make work for you, just remove the `-i` flag (or wait until #18 is merged, that adds support for non-stdin)

**Comment by p00f** [comment]
My bad, I misunderstood the `-i` flag. I thought it meant stdin
