### ISSUE TITLE
Neovim is culturally moving towards `formatexpr`

### ISSUE THREAD

**Issue by Diablo-D3** [mhartington/formatter.nvim#246]
An excerpt from my dotfiles:

```lua
function Formatexpr()
    local lnum = vim.v.lnum;
    local count = vim.v.count;
    require("formatter.format").format("", "", lnum, (lnum + count + 1), { lock = true })
end

vim.o.formatexpr = "v:lua.Formatexpr()"
```

With this, I can just activate `gq` (including on visual selections) and it works as expected with no other configuration changes.

Something similar should either be documented or codified into formatter.nvim.

**Comment by mhartington** [comment]
Not sure what you’re basing the claim that neovim is “culturally” moving towards formatexpr. 


we could add docs, and would accept a PR if you’d like to make it.
