### ISSUE TITLE
Simplify config for common cases

### ISSUE THREAD

**Issue by elihunter173** [mhartington/formatter.nvim#25]
Currently the config for formatters is an array-like table of functions, but for most filetypes I only use a single formatter and for most formatters the function just returns a static table. I think it would be more ergonomic to make it so that
1. Formatters can be optionally specified by tables instead of functions if they don't need anything dynamic.
2. The array-like table of formatters can be optionally replaced with a single formatter value (that is a function or also a formatter table if 1 is implemented too).

So for example with both of these implemented, I could do this to a snippet of my config.

```lua
-- Old
require("formatter").setup {
  filetype = {
    python = {
      function()
        return {exe = "black", args = {"-"}, stdin = true}
      end,
    },
    rust = {
      function()
        return {
          exe = "rustfmt",
          args = {"--edition=2018", "--emit=stdout"},
          stdin = true,
        }
      end,
    },
  },
}

-- Simplified
require("formatter").setup {
  filetype = {
    python = {exe = "black", args = {"-"}, stdin = true},
    rust = {
      exe = "rustfmt",
      args = {"--edition=2018", "--emit=stdout"},
      stdin = true,
    },
  },
}
```

I've skimmed the codebase and I'm pretty confident I could implement this if there's interest.

**Comment by mhartington** [comment]
I had originally thought about doing static tables, but to keep it consistent for users/maintainers, a function is required. Some formatters require that a file name be passed in, which cannot be derived from a function

```
local prettierConfig = function()
  return {
    exe = "prettier",
    args = {"--stdin-filepath", vim.api.nvim_buf_get_name(0), "--single-quote"},
    stdin = true
  }
end
```

And so far, that's worked really well. I'm not really thinking about changing it

**Comment by elihunter173** [comment]
That's fair enough. Any thoughts on 2? So you wouldn't have to specify a table if you only have one formatter?

**Comment by mhartington** [comment]
I mean, it _could_ work, but I don't really see the benefit. Since it's again having to type check if something is a table vs a function internally. The way it is now provides a consistent experience. Thanks for the idea, but I like the way things are currently.
