### ISSUE TITLE
ESLint not working

### ISSUE THREAD

**Issue by mralj** [mhartington/formatter.nvim#26]
Hello,

Firstly thank you very much for putting your effort & time into this project.

I have trouble getting ESLint (and `prettier-eslint`) working with this plugin.

1. I have both `eslint` and `prettier-eslint` installed globally
2. `prettier` works fine
3. eslint works with [lukas-reineke/format.nvim](https://github.com/lukas-reineke/format.nvim)

Here is my setup:

```
require('formatter').setup({
  logging = false,
  filetype = {
    typescriptreact = {
       function()
          return {
            exe = "eslint",
            args = {"--stdin","--stdin-filepath", vim.api.nvim_buf_get_name(0) },
            stdin = true
          }
        end
   		}
	}
})
```

And the error I am getting is `Failed to run formatter eslint` (same goes for ` prettier-eslint`), and if I am not mistaken, this setup is the same as in one of the [previous issues](https://github.com/mhartington/formatter.nvim/issues/20#issuecomment-749125690)

**Comment by mhartington** [comment]
Do you have a sample project I could inspect? As far as I know, eslint can't be called directly like that, since it's not a formatter that outputs code in  a way we understand.

**Comment by lukas-reineke** [comment]
eslint can fix "format" some issues.
According to this, you need to run it with `--fix-dry-run` https://github.com/eslint/eslint/issues/9076#issuecomment-321883359

But it's not working for me :thinking: eslint fixes issues fine with `--fix`, but with `--fix-dry-run` I get no output on either stdout or stderr.
Maybe something in my setup is wrong

You can use https://github.com/mhartington/formatter.nvim/pull/18 and run it as non-stdin, that should work.

**Comment by mralj** [comment]
Thank you very much for helping me out with this!

I've used #18, and it worked 🎉

Just in case somebody comes across this, this was my setup:

```
        function()
          return {
            exe = "eslint",
            args = {"--stdin-filename", vim.api.nvim_buf_get_name(0), "--fix", "--cache"},
            stdin = false
          }
        end
      },

```

Also, current `master` works with [prettier-eslint-cli](https://github.com/prettier/prettier-eslint-cli), which is basically the same as running prettier and  then ESLint (the reason it wasn't working for me before is that I was stupid and just installed `prettier-eslint`, not `prettier-eslint-cli`), the setup is the same as you mentioned [here](https://github.com/mhartington/formatter.nvim/issues/20#issuecomment-749125690)

```
        function()
          return {
            exe = "prettier-eslint",
            args = {"--stdin", "--stdin-filepath", vim.api.nvim_buf_get_name(0)},
            stdin = true
          }
        end

```

Performance-wise, I think they run about the same, but either way  `eslint --fix` is too slow 😩

Once again, thanks for helping out with this!
