### ISSUE TITLE
Feature request: disable formatting for a particular buffer

### ISSUE THREAD

**Issue by llimllib** [mhartington/formatter.nvim#27]
Sometimes I'm working on a piece of code and I don't want to format it on save - maybe it's somebody else's code or it's formatted in a particular way.

Ale has `:let b:ale_fix_on_save=0` which I use for this purpose, would be nice to have something like that for this library

**Comment by mhartington** [comment]
Yeah, I can see this being nice to have. I'll have some time coming up that I can look at adding this!

**Comment by mhartington** [comment]
Closing as this has been added. You can use the buffer variable `b:formatter_skip_buf` to disable formatter for a specific buffer.

**Comment by llimllib** [comment]
Thanks! apologies that I was so unhelpful in testing it, time got away from me
