### ISSUE TITLE
Why R language formatter not work?

### ISSUE THREAD

**Issue by yech1990** [mhartington/formatter.nvim#28]
I install formatter.nvim and it works for many languages. But for R language, I configure the `styler` formatter with this snippet.

```lua
r = {
        -- styler
        function()
          return {
            exe = "R",
            args = {
              "--slave",
              "--no-restore",
              "--no-save",
              "-e",
              "con<-file('stdin');out<-styler::style_text(readLines(con));close(con);print(out)",
              "2>/dev/null"
            },
            stdin = true
          }
        end
      }
```

But formatter.nvim keep reporting `Formatter: failed to run formatter R`

**Comment by yech1990** [comment]
I have already install the styler R package, and this tools works in command line mode.

Could you help for to find out the problem. I can not find debug mode in "formatter.nvim".

**Comment by mhartington** [comment]
1) Do you have a file sample? 
2) What's the command lines usage? 


I dont use R so Im a bit out of the loop here, so any tips for a non-R person be helpful.

**Comment by yech1990** [comment]
Hi @mhartington,

Any R script is ok. You can write a R script like this:

```R
print(   1 +   1)
```


The command line usage is:

```bash
cat test.R | R --slave -e 'con <- file("stdin"); styler::style_text(readLines(con)); close(con)'
````

**Comment by yech1990** [comment]
BTW, the `styler` package should be installed first. 
- Open R console.
- run `install.package("styler")`

**Comment by mhartington** [comment]
Ok, so the the `con <- file("stdin"); ` bits. On the command line, it's passed as a string, which is correct. But in your config, it's not. 

```
  r = {
    function()
      return {
        exe = "R",
        args = {
          "--slave",
          "--no-restore",
          "--no-save",
          "-e",
          "'con <- file(\"stdin\"); styler::style_text(readLines(con)); close(con)'",
          "2>/dev/null"
        },
        stdin = true
      }
    end
  }
```

It's a very _subtle_ change, but it's how the command is parsed.  Similarly, this is how neoformat does it as well.

https://github.com/sbdchd/neoformat/blob/master/autoload/neoformat/formatters/r.vim#L5-L11


Tested this and it worked fine. Closing.

**Comment by yech1990** [comment]
It works!

**Comment by yech1990** [comment]
Sorry about that, L5-L11 in neoformat is written by me, but I totally forget about these.

**Comment by mhartington** [comment]
It happens! Cheers!
