### ISSUE TITLE
shellescape buffer name

### ISSUE THREAD

**Issue by rudotriton** [mhartington/formatter.nvim#30]
I have a system created path that has a space in it and which I unfortunately cannot get around of. I had naively copied the config in the readme which I'm sure works almost every time, but doesn't escape the path.

```lua
function()
	return {
		exe = "prettier",
        args = {"--stdin-filepath", vim.api.nvim_buf_get_name(0), '--single-quote'},
        stdin = true
	}
end
```

It's not really an issue per se, rather just a heads up for people that may come across something like this.

Anyway, I know almost nothing about nvim api or lua, so my solution right now is this:

```lua
local escape_path = function(path)
   return vim.api.nvim_eval('shellescape(\'' .. path .. '\')')
end
```

You can close this, or mention it, or conjure a more robust example for the readme.

**Comment by mhartington** [comment]
Since the config is mostly in user space, we should probably document this instead. A way to deal with this is 

```
function()
	return {
	  exe = "prettier",
          args = {"--stdin-filepath", vim.fn.fnameescape(vim.api.nvim_buf_get_name(0)), '--single-quote'},
          stdin = true
	}
end
```

Since not every formatter needs to have the file name in the args, there's not a whole lot we can do to verify that it's escaped.
