### ISSUE TITLE
Example of using multiple formatters for one file type?

### ISSUE THREAD

**Issue by lougreenwood** [mhartington/formatter.nvim#31]
Hi, thanks for the great tool!

Could you share an example of how to use multiple formatters for one file type in sequence? I'm not familiar with lua, so not sure of the syntax for this (or if it's even possible?)

I'm, trying to run `prettier_d` followed by `eslint_d`, as described here: https://github.com/josephfrazier/prettier_d/issues/2#issuecomment-311764841

**Comment by mhartington** [comment]
👋 So you'd basically just setup a new entry for each formatter you want to run...

```
local prettierFmt = function()
  return {
    exe = "prettier",
    args = {"--stdin-filepath", vim.api.nvim_buf_get_name(0), "--single-quote"},
    stdin = true
  }
end

local eslintFmt = function()
  return {
      exe = "eslint_d",
      args = { '--stdin', '--stdin-filename', vim.api.nvim_buf_get_name(0), '--fix-to-stdout' },
      stdin = true
    }
end

formatter.setup(
  {
    logging = false,
    filetype = {
      typescript = {prettierFmt, eslintFmt}
    }
  }
)

```

Hope this helps.
