### ISSUE TITLE
This project is about to become stale. What to do?

### ISSUE THREAD

**Issue by tjex** [mhartington/formatter.nvim#342]
At this point its pretty clear that mhartington is not able to give attention to this project.
Issues and PRs are stacking up. Also PRs that fix existing issues. Which is always a telling sign when those PRs are also not being merged.

So, what to do?

There aren't any forks that are being actively developed. I guess the majority with any commits (most have 1 commit) exist for PRs.

Has anyone been thinking of forking and maintaining?

@mhartington . Would be great to get some idea of the future. At the very least a recognition that you could update the Readme with a link to the successor fork, if one does get created.

It's not at all a "call out" for dropping the project. It would just be a shame for this project to rot completely and everyone have to bounce around and find some other project and/or miss the memo of a successor fork.

**Comment by CrociDB** [comment]
It's sad to see that many of the fixes (such as yours) and additions are not making it in. If anyone decides to fork and maintain it, or @mhartington opens it for more maintainers, I would volunteer to help.

**Comment by tjex** [comment]
Thanks for getting back in touch and working through the PRs!
I'm tempted to help out, but already have a lot to handle over on [zk](https://github.com/zk-org) where I'm more or less also holding the fort alone while also job hunting for a dev job and writing a masters thesis. But, I could still come on board to at least review PRs / triage bugs. I'll sit with the idea for a bit and see...

**Comment by boris-stepanov** [comment]
I'd also join at least as a reviewer for some of the languages I use myself. It looks like we don't have one person to take on all the development, so a group of maintainers might work.
