### ISSUE TITLE
Why does this plugin install luarocks/hererocks without my consent?

### ISSUE THREAD

**Issue by gmr458** [mhartington/formatter.nvim#348]
I just updated my plugins and for some reason it starts installing hererocks, I don't have that plugin listed anywhere in my configuration.

**Comment by monstahcode** [comment]
same here

**Comment by mhartenbower** [comment]
I believe it's because #346 introduced a rockspec. You can disable luarocks in your lazy setup with `rocks = {enabled = false,}`.

**Comment by mortymacs** [comment]
> I believe it's because #346 introduced a rockspec. You can disable luarocks in your lazy setup with `rocks = {enabled = false,}`.

Could you please share your configuration? I tried this, but still getting error:

```lua
  {
      "mhartington/formatter.nvim",
      event = "VeryLazy",
      opts = {
          rocks = {
            hererocks = false,
            enabled = false,
        },
      },
  },
```

**Comment by mhartington** [comment]
I just reverted the parts of #346 that included tests for now. Sorry for the confusion folks.
