### ISSUE TITLE
Namespace conflict with lspconfig

### ISSUE THREAD

**Issue by webdavis** [mhartington/formatter.nvim#35]
Hi, I'm getting the following error message when I run `:Format` on servers registered with [nvim-lspconfig](https://github.com/neovim/nvim-lspconfig):

```
RPC[Error] code_name = MethodNotFound, message = "method textDocument/formatting is not supported by any of the servers registered for the current buffer"
```

However, if I add the following command to `plugin/formatter.vim`:

```vim
command! -nargs=? -range=%
      \ -complete=customlist,s:formatter_complete
      \ Formatter lua require("formatter.format").format(<q-args>, <line1>, <line2>, false)
```

and then run `:Formatter`, formatter.nvim runs successfully. I'm not really sure about the internals of this plugin and nvim-lspconfig but this seems like a namespace conflict to me. Thoughts?

**Comment by mhartington** [comment]
Mmm, probably not a conflict with the plugin, but maybe your setup. Can you share a minimal rc/setup?

**Comment by webdavis** [comment]
Here it is. It's split between two files. It seems to only be happening when `sumneko_lua` language server is started via `:LspStart lua`. If I run `:LspStop` `:Format` starts working again.

```lua
-- Filename: lua/config/lsp/lua.lua
local M = {}

M.settings = {
  Lua = {
    runtime = {
      -- LuaJIT in the case of Neovim.
      version = "LuaJIT",
      path = vim.split(package.path, ";")
    },
    diagnostics = {
      -- Get the language server to recognize the `vim` global.
      globals = {"vim"}
    },
    workspace = {
      -- Make the server aware of Neovim runtime files.
      library = {
        [vim.fn.expand("$VIMRUNTIME/lua")] = true,
        [vim.fn.expand("$VIMRUNTIME/lua/vim/lsp")] = true
      },
      preloadFileSize = 1000
    },
    telemetry = {
      enable = false
    }
  }
}

return M
```

```lua
-- Filename: lua/config/lsp/init.lua
local function setup_servers()
  require "lspinstall".setup()

  -- Get all installed servers
  local servers = require "lspinstall".installed_servers()
  -- ... and add manually installed servers here:
  -- table.insert(servers, 'clangd')

  for _, server in pairs(servers) do
    local config = make_config()

    -- Language specific config.
    if server == "lua" then
      config.settings = require "config.lsp.lua".settings
    end

    require "lspconfig"[server].setup(config)
  end
end

setup_servers()

-- Automatically reload after `:LspInstall <server>` so we don't have to restart neovim.
require "lspinstall".post_install_hook = function()
  setup_servers() -- Reload installed servers.
  vim.cmd("bufdo e") -- This triggers the FileType autocmd that starts the server.
end
```

**Comment by mhartington** [comment]
No clue. Nothing in your code even references packages that formatter ships under. Also the error message looks pretty sus to me.

>RPC[Error] code_name = MethodNotFound, message = "method textDocument/formatting is not supported by any of the servers registered for the current buffer"

This would indicate that whatever `Format` is calling in your setup is actually from lsp-config. We do not use lsp in formatter, so that error is not from us.

**Comment by lukas-reineke** [comment]
Can you post the output of `:command Format`

**Comment by webdavis** [comment]
```vim
:verbose command Format
    Name              Args Address Complete    Definition
    Format            0                        lua vim.lsp.buf.formatting()
        Last set from ~/.local/share/nvim/site/pack/packer/start/nvim-metals/plugin/metals.vim line 5
    FormatWrite       ?    %       customlist  lua require("formatter.format").format(<q-args>, <line1>, <line2>, true)
        Last set from ~/.local/share/nvim/site/pack/packer/start/formatter.nvim/plugin/formatter.vim line 9
```

(That was a nifty trick. Thanks for sharing that!)

So it looks like it's conflicting with the Scala language server plugin [scalameta/nvim-metals](https://github.com/scalameta/nvim-metals). Is there any way that I can ensure that formatter.nvim takes precedence?

**Comment by webdavis** [comment]
I put the following line in my `wbthomason/packer.nvim` config:

```lua
use {"scalameta/nvim-metals", ft = {"scala",}}
```

Not sure if there's a better way to do this though.

**Comment by lukas-reineke** [comment]
> Is there any way that I can ensure that formatter.nvim takes precedence?

I think the only way is to make sure formatter.nvim is loaded after nvim-metals.

**Comment by webdavis** [comment]
I couldn't force it to load after nvim-metals using `packer.nvim`, even when using the `after` key. So I put the following in my lua config:

```lua
vim.api.nvim_exec(
  [[
    function! Formatter_complete_custom(...)
      return luaeval('require("formatter.complete").complete(_A)', a:000)
    endfunction

    command! -nargs=? -range=% -complete=customlist,Formatter_complete_custom Formatter lua require("formatter.format").format(<q-args>, <line1>, <line2>, false)
  ]],
  false
)

vim.api.nvim_set_keymap("n", "<Leader>gq", ":<C-u>Formatter<CR>", {noremap = true, silent = false})
```

**Comment by mhartington** [comment]
well that's silly...also TIL `verbose command` as well. I just opened a ticket on the metals repo about prefixing their format command since the rest of their commands are prefixed as well. I guess we'll keep this open for now.

**Comment by webdavis** [comment]
Nice! Hopefully that goes through. Thanks for the help.

**Comment by mhartington** [comment]
https://github.com/scalameta/nvim-metals/discussions/123

**Comment by ckipp01** [comment]
Sorry to lead you down a rabbit whole with this one. If you do a `:PackerUpdate`, it's fixed now in `nvim-metals`.

**Comment by mhartington** [comment]
Thank you @ckipp01
