### ISSUE TITLE
6cc7d40 possible regression

### ISSUE THREAD

**Issue by rudotriton** [mhartington/formatter.nvim#37]
I use [stylua](https://github.com/JohnnyMorganz/StyLua) which i noticed didn't work anymore. I had just previously dowloaded a new version for that so at first I suspected it had changed something, but I also ran a quick bisect on formatter. Stylua works with 87e2de6 but not with 6cc7d40

The setup for lua looks like this:

```lua
lua = {
  function()
    return {
      exe = "stylua",
      args = { "--config-path", "~/.config/.stylua.toml", "-" },
      stdin = true,
    }
  end,
},
```

Is this expected and do I need to change my config after the last change or is it something else?

**Comment by mhartington** [comment]
Is there an error message printed out? I just tested real quick and things seem to work. Not sure if the config path is the issue 🤔 

Do you have a sample config file?

**Comment by rudotriton** [comment]
The error was the usual `failed to run formatter stylua`.

The path was the issue. The `~` doesn't work anymore. I can do `vim.fn.expand` to fix that.

Thanks, I think that solves it then

**Comment by mhartington** [comment]
🤔 Odd, but good to know. We did a small change to how the cmd and args get joined together, so I'll look at that.

**Comment by lukas-reineke** [comment]
Before we ran the command in the configured shell, now it runs directly.
So if the tool you are using can't expand `~`, it won't.

We did this because shell escaping can be a pain, but maybe running it with shell is actually more what the user expects :thinking:

**Comment by mhartington** [comment]
>we ran the command in the configured shell, now it runs directly.

Where was this change? Wasn't really clear when I reviewed it.
