### ISSUE TITLE
User autocommands

### ISSUE THREAD

**Issue by lukas-reineke** [mhartington/formatter.nvim#4]
Would be nice to have User autocommands like `FormatPre`, `FormatPost`

**Comment by mhartington** [comment]
Should these run after each formatter? Or after all the formatters defined for a given filetype?

**Comment by lukas-reineke** [comment]
I think they should run whenever we touch the buffer. For read or write

**Comment by mhartington** [comment]
Seeing as this was part of the #3, is this ok to close?
