### ISSUE TITLE
How to debug on failure?

### ISSUE THREAD

**Issue by winston0410** [mhartington/formatter.nvim#43]
I am trying to set up `shfmt` for formatting `sh` with this plugin. I got the error `Formatter: failed to run formatter shfmt` and I have no idea how to fix it. How can debug the issue? I found the `logging` function does not work as well.

This is my current config for `shfmt`

```lua
local function shfmt()
  return {
	exe = "shfmt",
	args = {"-w", vim.api.nvim_buf_get_name(0)},
	stdin = true
  }
end
```

**Comment by winston0410** [comment]
I would love to contribute to the README and list the config for formatter in various language as well. Best of luck with the project.

**Comment by mhartington** [comment]
Closing as there hasn't been any comments here in a bit. If this is still a problem, please open a new issue!
