### ISSUE TITLE
add option to toggle enable/disable

### ISSUE THREAD

**Issue by yofriadi** [mhartington/formatter.nvim#44]
Hi, since this is formatter (on save most likely) could you add this toggle option for easy play around with language formatting, because I messed up the config for lua itself and no easy workaround other than deleting the nvim config.

I do like use `;` instead of `,` for table, but typo it with `'` then my config became error, everytime I change it will fomat it to the error.

**Comment by lukas-reineke** [comment]
We don't add any autocommands in the plugin. You probably copied the example from the README?

I don't think it would make sense to add a feature to disable the `Fromat` command itself. If you want to toggle formatting on save, you should add your own check inside the autocommand.

Specifically for your issue, if you want to run a command once without triggering any autocommands, you can do that with `:noautocmd`
So you can do `:noautocmd write` and it will not format. Just be aware that it will not run any other autocommands on save either.

**Comment by yofriadi** [comment]
ah I see I didn't know there is the opposite `autocmd`, thanks
