### ISSUE TITLE
How to make FormatWrite silent?

### ISSUE THREAD

**Issue by bsander** [mhartington/formatter.nvim#48]
I followed the README instructions to setup format on save by adding this to my config:

```lua
vim.api.nvim_exec([[
augroup FormatAutogroup
  autocmd!
  autocmd BufWritePost *.js,*.rs,*.lua FormatWrite
augroup END
]], true)
```

This works nicely, though every time a formatter makes a change, I get a message in my statusline that reads something like this:

```
Formatter: Finished running luafmt
"vim/lua/plugin/formatter.lua" 53L, 810C [w]
Press Enter or type command to continue
```

Requiring me to press Enter to acknowledge the message, which is distracting.

Somehow, adding `silent!` to the autocmd doesn't have an effect. What can I do to make the formatting happen silently? I don't want to increase my cmdheight for this.

**Comment by mhartington** [comment]
I think this is probably an upstream issue with neovim. Internally there's a print function that uses `out_write` to print messages.

```
function util.print(msg)
  local txt = string.format("Formatter: %s", msg)
  vim.api.nvim_out_write(txt .. "\n")
end
```

We _could_ use `echo`, though not sure it works the same way. I'll ping the team about it.

**Comment by bsander** [comment]
Thanks! So does that mean there's not much I can do in the meantime?

**Comment by mhartington** [comment]
Pretty sure. Unless mr @tjdevries knows more (which he probably does)

**Comment by andrew-t-james** [comment]
👀 Also curious about this, thanks for all the work on this! Been really liking lua for the configs.

**Comment by tjdevries** [comment]
If you never want any prints, you can just monkey patch over the print function:

```lua
require('formatter.util').print = function() end
```

Not sure about the other bits off-hand :)
