### ISSUE TITLE
Running Format/FormatWrite wipes out all existing marks

### ISSUE THREAD

**Issue by Racle** [mhartington/formatter.nvim#49]
Running Format/FormatWrite removes all marks on file.

vim-prettier fixed issue this way: https://github.com/prettier/vim-prettier/pull/300

That would be great addition to formatter.nvim if you could lockmarks somehow.
Not 100% sure if that can be done in this plugin, but it's done in vim-prettier already.

(I also tried to use `:lockmarks FormatWrite`, but that doesn't work.).

**Comment by lukas-reineke** [comment]
Using `nvim_buf_set_text` instead of `nvim_buf_set_lines` should fix this #22

**Comment by mhartington** [comment]
Closing as we'll keep this with #22
