### ISSUE TITLE
"Formatter: No change necessary with nil" from condtional FormatWrite in autocmd

### ISSUE THREAD

**Issue by Melkster** [mhartington/formatter.nvim#54]
I've use [the recommended `autocmd`](https://github.com/mhartington/formatter.nvim#format-on-save)  to format on write, which I tried to make depend on a buffer variable so that I can toggle autoformatting on and off. However, for some reason when putting `FormatWrite` in an `if` in the `autocmd` I get the following message after writing to a file: "Formatter: No change necessary with nil"

# To reproduce

1. Use the following `init.vim`:

    ```vim
    call plug#begin('~/.vim/bundle')
      Plug 'mhartington/formatter.nvim'
    call plug#end()

    lua << EOF
    require('formatter').setup {
      filetype = {
        lua = {
          function()
            return {
              exe = 'lua-format',
              stdin = true
            }
          end
        }
      }
    }

    vim.b.format_on_write = 1

    vim.api.nvim_exec([[
      augroup FormatOnWrite
        autocmd!
        autocmd BufWritePost * if b:format_on_write | FormatWrite | endif
      augroup END
    ]], true)
    EOF
    ```

2. Try to write to a lua file, for instance this one:

    ```lua
    foo( bar)

    local foo  = 1
    ```

    This outputs: "Formatter: No change necessary with nil"

3. If you replace `autocmd BufWritePost * if b:format_on_write | FormatWrite | endif` with `autocmd BufWritePost * FormatWrite` the file gets autoformatted as expected.

**Comment by mhartington** [comment]
Hmmm, not sure about this one. Any thoughts @lukas-reineke ?

**Comment by lukas-reineke** [comment]
Vimscript is hard. 

We have to specify that the command does not use `|` itself, so you can use it to chain.

I made a PR with a fix.

Here are the relevant help docs `:h :command-bar`

**Comment by Melkster** [comment]
Thank you, works great now!
