### ISSUE TITLE
Lua error when running :Format Expected lua number

### ISSUE THREAD

**Issue by MasterGordon** [mhartington/formatter.nvim#55]
Hi, when I am trying to run :Format I am getting the following error:
E5108: Error executing lua ...fig/nvim/plugged/formatter.nvim/lua/formatter/format.lua:39: Expected lua number

I am running NVIM v0.5.0-dev+1405-g2f0e5e7e6 and LuaJIT 2.1.0-beta3
I have also tried NVIM v0.5.0 RELEASE and NVIM v0.6.0-dev

Plugin has been installed via VimPlug and is running the example config.

**Comment by mhartington** [comment]
Im not able to replicate this. How are you getting this? I need a test reproduction as well as some config.

**Comment by MasterGordon** [comment]
I can reproduce it with this config

init.vim
```vimscript
call plug#begin()
Plug 'mhartington/formatter.nvim'
call plug#end()

" Formatter
luafile $HOME/.config/nvim/plugins/formatter.lua
```

$HOME/.config/nvim/plugins/formatter.lua
```lua
require("formatter").setup(
  {
    logging = false,
    filetype = {
      lua = {
        -- luafmt
        function()
          return {
            exe = "luafmt",
            args = {"--indent-count", 2, "--stdin"},
            stdin = true
          }
        end
      }
    }
  }
)

vim.api.nvim_exec(
  [[
augroup FormatAutogroup
  autocmd!
  autocmd BufWritePost *.lua,*.tsx,*.ts,*.js,*.jsx,*.json FormatWrite
augroup END
]],
  true
)
```

**Comment by mhartington** [comment]
Do you have some sample code? still not able to replicate this.

**Comment by MasterGordon** [comment]
The .config/nvim/plugins/formatter.lua from my last comment would be a example file.
