### ISSUE TITLE
Run vim commands

### ISSUE THREAD

**Issue by ErikReider** [mhartington/formatter.nvim#59]
Is there a way to execute vim or lua commands like `vim.cmd("call Uncrustify('VALA')")`? This would be nice for formatters like uncrustify that doesn't replace any text but prints the formatted content in the terminal instead.

This is my current solution:
``` lua
vala = {
    function()
        vim.cmd("call Uncrustify('VALA')")
        return {exe = "echo", args = {}, stdin = false}
    end
},
```

**Comment by mhartington** [comment]
No this is not possible. If you want to use uncrusitfy, you must use `stdin`


```
function ()
  return {
    exe = "uncrustify",
    args = {"-q", "-l C"},
    stdin = true
  }
end
```

**Comment by melkster** [comment]
I would really like to have this feature as well in order to call [nvim-lsp-ts-utils](https://github.com/jose-elias-alvarez/nvim-lsp-ts-utils)'s `:TSLspImportAll` (imports missing modules) and `:TSLspOrganize` (organizes imports) in TypeScript files, before or after formatting the file with Prettier like so:

```lua
{
  exe = 'prettier',
  args = { '--stdin-filepath', api.nvim_buf_get_name(0) },
  stdin = true
}
```

**Comment by mhartington** [comment]
Using basic vim auto-cmds, you can do this.

```lua

vim.api.nvim_exec([[
augroup FormatAutogroup
  autocmd!
  autocmd BufWritePre *.js,*.rs,*.lua TSLspImportAll
augroup END
]], true)

vim.api.nvim_exec([[
augroup FormatAutogroup
  autocmd!
  autocmd BufWritePost *.js,*.rs,*.lua FormatWrite
augroup END
]], true)
```

No need to add anything to this plugin.

**Comment by melkster** [comment]
@mhartington This was the first solution that I tried but they seem to clash because when writing to the buffer I get the error message: `Formatter: Buffer changed while formatting, not applying formatting`.
