### ISSUE TITLE
run formatters in sequence

### ISSUE THREAD

**Issue by lukas-reineke** [mhartington/formatter.nvim#6]
With the current refactor branch the formatter run in parallel.
They will overwrite each other.

We will need to change them to run in sequence.
That should be pretty easy, but the config currently defines them as key value pairs. There is no guaranteed order in lua tables for key value pairs.
I think users will want to define the order formatters run in.
This would mean we need to change the structure of the config and break everyone that's currently using it :(

**Comment by mhartington** [comment]
We should be able to control the flow in the loop. Going to research this a bit more to figure out what the best solution is

**Comment by lukas-reineke** [comment]
In my implementation I use callbacks.
I have a stack of formatter, take the first one and call format and pass a callback.
Then the callback gets called in `on_exit` and I take the next formatter from the stack until there are no formatters left.

Should work here too, the only problem is with the config. I used arrays for this, so users can configure the order. But here the formatter are key value pairs.

**Comment by lukas-reineke** [comment]
oh actually we could just support both :thinking: 
tables are tables in lua, this is totally valid

```
local foo = {
    hello = "world",
    "foo",
    "bar"
}

for a, b in pairs(foo) do
    print(a, b)
end
```

Its ugly, but we could add ordering without breaking backwards compatibility

**Comment by mhartington** [comment]
Went with key/value pairs here since the config needs to be built from a function for certain formatter. Like prettier needs to be passed a buffer name in the cmd args

```
  javascript = {
      prettier = function()
        return {
          exe = "prettier",
          args = {"--stdin-filepath", vim.api.nvim_buf_get_name(0), '--single-quote'},
          stdin = true
        }
      end
  },```

If it's a table or string, that can't be done, since the `nvim_buf_get_name` would just be the buffer on startup.

**Comment by mhartington** [comment]
AH I see what you mean about the callback! I'll try that out, it looks like it has potential!

**Comment by mhartington** [comment]
Ok, took some inspiration from what you had in your version, and applied it to the refactor branch. Formatters are now running sequentially!

**Comment by alex-popov-tech** [comment]
hey guys, any chances that will be merged soon?
For javascript/typescript it could be useful to run prettier and then eslint

**Comment by mhartington** [comment]
@alex-popov-tech this should already be in master

**Comment by alex-popov-tech** [comment]
@mhartington cool! can you please update readme with an example then?

**Comment by mhartington** [comment]
The readme and example where updated with #12

**Comment by alex-popov-tech** [comment]
@mhartington thanks, get it.
But you did this example with multiple formatters in pr description, not in readme, so i was confused...i can  create pr and update readme from your pr description, if you want...but i think this feature should be mentioned in master readme anyways :)
