### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by PierreMacherel** [mhartington/formatter.nvim#60]
Could you add windows support ?
the line delimiter in Windows os is `\`. This is problematic in two places :
https://github.com/mhartington/formatter.nvim/blob/9866548f1c543ba90d7bb8a62c4fa939a5dcba46/lua/formatter/util.lua#L105
https://github.com/mhartington/formatter.nvim/blob/9866548f1c543ba90d7bb8a62c4fa939a5dcba46/lua/formatter/util.lua#L112

**Comment by mhartington** [comment]
would happily accept a PR for this! should just be an if/else check for the deliminator
