### ISSUE TITLE
Question: Is range formatting supported?

### ISSUE THREAD

**Issue by AckslD** [mhartington/formatter.nvim#62]
Is it possible to select some lines in visual mode and format those?

**Comment by mhartington** [comment]
Yes this is already supported.

**Comment by AckslD** [comment]
Thanks @mhartington. I only see this
```
nnoremap <silent> <leader>f :Format<CR>
```
in the README so wasn't sure what the keybind/command would be?

**Comment by forrestfwilliams** [comment]
Hey @AckslD, did you figure out how to run formatting for a selection in visual mode? I'm confused as well.

**Comment by AckslD** [comment]
@forrestfwilliams, doesn't just selection some lines and type `:Format<CR>` (explicitly `'<,'>Format<CR>`) work for you?
