### ISSUE TITLE
Option for enabling/disabling formatter

### ISSUE THREAD

**Issue by mtrajano** [mhartington/formatter.nvim#69]
I work with some large files and have the formatter running on an auto event. Even though the formatters run async there can still be some lag reading the file from the tmp buffer every time there is a save. It would be nice to have the ability to disable the formatter for these types of buffers either through a buffer variable ex. `vim.b.formatter_disable = 1`, or disable specific formatteers for them, something like:
```
{
  filetype = {
    php = {
      function()
        local line_count = vim.api.nvim_buf_line_count(0)

        return {
          ...
          disable = line_count > 1000
        }
      end
    }
  }
}
```

**Comment by lukas-reineke** [comment]
Why not make this variable yourself and check in your autocommand? No need to add anything to the plugin

**Comment by mtrajano** [comment]
That's true, you could do that. Although I still think it could be worth it to have an interface there for toggling formatting on and off such as a `FormatterToggle` command, instead of having to hack something together yourself. I do see your concern about adding more things to the plugin, though. 

The idea was also to have more fine-grained control of which linters should run. In the example above it was based off the the line count, but it could also be a list of `pwd` where the linter shouldn't run. Would the idea then be to run the formatter setup function on an `BufEnter` or `DirChanged` autocmd which would set up the right linter functions? I guess I just always thought of the setup function as only being needed to run once and the configuration itself would control which linters should and shouldn't run. 

Feel free to close this ticket if you want, as you can still achieve those things without these changes

**Comment by lukas-reineke** [comment]
I don't think adding `FormatterToggle` makes sense, because the plugin doesn't do any auto-formatting. It just provides commands, when to run or not run these commands is up to the user.

> The idea was also to have more fine-grained control of which linters should run

You can already do this, and you don't need to run the setup function again. The formatter configuration is exposed as a function to the user that runs every time the formatter runs. You can do custom logic in there.
To take your example, if you don't want to run a formatter if the file is too big, you can do this
 
```lua
{
    filetype = {
        php = {
            function()
                if vim.api.nvim_buf_line_count(0) > 1000 then
                    return {}
                end

                return {
                    exe = "foo"
                }
            end
        }
    }
}
```

Returning an empty table will just skip that formatter.

**Comment by lukas-reineke** [comment]
> Returning an empty table will just skip that formatter.

Maybe it doesn't, actually. But we should support this :sweat_smile:

**Comment by mtrajano** [comment]
Yup it doesn't currently, it expects `exe` and `stdin`  options to be passed in I think. That solution would make sense to me as well (an empty table would disable that linter)

**Comment by lukas-reineke** [comment]
I made a PR to support this now

**Comment by mhartington** [comment]
Looking through this, I think there's probably a better way to do this. Neoformat had an approach where formatters would be applied globally with 

```
let g:neoformat_enabled_python = ['autopep8', 'yapf', 'docformatter']
```

Then have buffer scoped version that users could customize

```
let b:neoformat_enabled_python = ['autopep8']
```

To me, this seems like a cleaner solution, though it could be more work to make sure it doesn't break existing setups.
Going to think about this.

**Comment by lukas-reineke** [comment]
But having just a buffer variable would not let you run custom logic to decide on each format call, like the example with linecount.

**Comment by Hrle97** [comment]
Can we close this? I feel like the current implementation is pretty good.

**Comment by mtrajano** [comment]
That’s fine by me, I agree with @lukas-reineke’s points

**Comment by Hrle97** [comment]
Seems like all is good so I'm closing this.
