### ISSUE TITLE
Need for "FormatWrite" command?

### ISSUE THREAD

**Issue by mhartington** [mhartington/formatter.nvim#7]
I merged it in during #3, but what's the point of "FormateWrite" command? 

Looking at something like Neoformat, they only have a single format command  and run the formatters regardless.
Seems like the right kind of approach, but open to hear out why.

**Comment by lukas-reineke** [comment]
Neoformat is not async. If you want to format on save you can just do this

```
augroup fmt
  autocmd!
  autocmd BufWritePre * undojoin | Neoformat
augroup END
```

But as formatted.nvim is, it's not that easy. You could listen on the `FormatterPost` autocommand and then write the buffer, but you then need to write custom logic as the user to check if buffer is modified. And there is also no way to know for which buffer the autocommand was triggered, so there could be race conditions.

But just with the `FormatWrite` command, all users have to do now is

```

augroup fmt
  autocmd!
  autocmd BufWritePre * FormatWrite
augroup END
```

And it just works

**Comment by mhartington** [comment]
Interesting. Though if the buffer is modified and someone attempts to call `Format` or `Format` write, I'm not seeing the changes get applied with the write logic in place

**Comment by lukas-reineke** [comment]
> Though if the buffer is modified and someone attempts to call `Format` or `Format` write, I'm not seeing the changes get applied with the write logic in place

Ah maybe the name is a bit unclear.
It's supposed to write the changes after formatting.
If the buffer already has unsaved changes and you call `Format` or `FormatWrite` nothing should happen. (Except when it's called with `!`)
This is in case you change the buffer in the time between calling format and the formatter being done.

The use case for `FormatWrite` is a user can save the buffer, and in the background formatter formats the buffer and saves it again. Only if there are changes, it's the right buffer and without autocommands so it's not an endless loop.
And you can just save and continue to work, if you modify the buffer before formatting is done, it won't overwrite anything without the bang.

**Comment by mhartington** [comment]
Hmm, so I think we should always have the formatter run regardless. I often write code and just need to format before actually writing to buffer. 

All in all, I don't think having the user manage things with `undojoin` is too problematic. Basically trying to keep the plugin itself super simple and letting the user customize the experience vs accounting for every situation that could arise.

**Comment by lukas-reineke** [comment]
Sorry the `undojoin` wasn't really relevant, I should have left it out.
My point is, without `FormatWrite` user _can not_ format on save, without writing their own implementation.

This doesn't work, because we are async

```
augroup fmt
  autocmd!
  autocmd BufWritePre * Format
augroup END
```

**Comment by mhartington** [comment]
Ahh, I see what you mean. Ok, thanks for the clarification!
