### ISSUE TITLE
Formatter for default filetype `["*"]` when no formatter is specified

### ISSUE THREAD

**Issue by mgnsk** [mhartington/formatter.nvim#75]
I previously used `lukas-reineke/format.nvim` and it had the option to specify a default formatter for any filetype.

Specifically, I'd like to use it to remove trailing whitespace:
```lua
require "formatter".setup {
    filetype = {
        ["*"] = {
            function()
                return {
                    -- remove trailing whitespace
                    exe = "sed",
                    args = {"-i", "'s/[ \t]*$//'"},
                    stdin = false
                }
            end
        }
    }
}
```

**Comment by rafamadriz** [comment]
You can do that with an autocommand and it will work on every filetype:
```viml
    augroup TrimTrailingWhiteSpace
        au!
        au BufWritePre * %s/\s\+$//e
        au BufWritePre * %s/\n\+\%$//e
    augroup END
```

**Comment by mgnsk** [comment]
> You can do that with an autocommand and it will work on every filetype:
> 
> ```viml
>     augroup TrimTrailingWhiteSpace
>         au!
>         au BufWritePre * %s/\s\+$//e
>         au BufWritePre * %s/\n\+\%$//e
>     augroup END
> ```

Thanks, that's really nice. There's a lifetime of discoveries to be made in every part of vim.

**Comment by lukas-reineke** [comment]
While yes, in this case you can use solve it with a substitution from within Vim, I still think it would be a good feature to have.

**Comment by nanozuki** [comment]
Providing a default formatter will make the config of autocmd to be easier:

```vimL
augroup FormatAutogroup
  autocmd!
  autocmd BufWritePost * FormatWrite
augroup END
```

**Comment by imbolc** [comment]
@nanozuki you can use this config right now - just suppress errors
```vim
augroup FormatAutogroup
  autocmd!
  autocmd BufWritePost * silent! FormatWrite
augroup END
```

**Comment by Hrle97** [comment]
id like to make a pr after #144 gets merged so waiting on that a bit

**Comment by Hrle97** [comment]
please check out #144 - it adds this feature as originally requested by @mgnsk

**Comment by vonbirdie** [comment]
I've got a use case where we're running a formatter across all file types and look for certain markers (as structured comments) and the formatter only runs on the content between the markers.

Is the idea here to have a fallback formatter if no other formatter runs or to have a wildcard formatter which could also run before all other formatters but formatters configured later in the ordered list can and will still run?

**Comment by mattdenner** [comment]
I've tried this out and it doesn't appear to work for me. The issue seems to be that, unless I specify at least one formatter for a file type, the `*` formatters don't get run.

If I have this configuration the no whitespace is stripped:
```lua
require('formatter').setup({
  filetype = {
    ['*'] = { require('formatter.filetypes.any').remove_trailing_whitespace, },
  },
})
```

If I have any empty array defined for a file type then the same result, e.g.:
```lua
require('formatter').setup({
  filetype = {
    javascript = {},
    ['*'] = { require('formatter.filetypes.any').remove_trailing_whitespace, },
  },
})
```

However, if I define a single formatter defined for the filetype then I get whitespace stripped, e.g.:
```lua
require('formatter').setup({
  filetype = {
    javascript = { function() return nil end, },
    ['*'] = { require('formatter.filetypes.any').remove_trailing_whitespace, },
  },
})
```

My lua skills are near zero but I think [this line](https://github.com/mhartington/formatter.nvim/blob/master/lua/formatter/config.lua#L85) ends up an array that contains `nil` as the first element in the first two cases. And then, I think, [this line](https://github.com/mhartington/formatter.nvim/blob/master/lua/formatter/format.lua#L32) fails because it's trying to call `nil()`. I am probably wrong with that though.

Is this a bug? Or PEBKAC?

**Comment by Hrle97** [comment]
@mattdenner That's an extremely good catch for someone that doesn't know `lua`. I tried this with luajit and it seems you nailed the heart of the problem:
```
> a = {}
> b = { 1 }
> c = { unpack(a), unpack(b) } 
> print(#c)
2
> print(c[1])
nil
> print(c[2])
1
```

However, it works as you would expect if the empty array is last:
```
> a = {}
> b = { 1 }
> c = { unpack(b), unpack(a) }
> print(#c)
1
> print(c[1])
1
> print(c[2])
nil
```

I'll make a PR resolving this and post it here in a bit.
