### ISSUE TITLE
Same file buffer in multiple windows, other buffer scrolls to top when formatting

### ISSUE THREAD

**Issue by mgnsk** [mhartington/formatter.nvim#76]
When working with long files, I tend to open the same file side-by-side in different positions. For vim, it's the same exact buffer. When formatting one file, the other file jumps to top, losing the scroll position. It happens with both stdin true or false.

Is this even possible to fix and is it somehow related to https://github.com/mhartington/formatter.nvim/issues/22?

**Comment by lukas-reineke** [comment]
This is the same issue as https://github.com/mhartington/formatter.nvim/issues/73#issuecomment-889575386

**Comment by mgnsk** [comment]
> This is the same issue as [#73 (comment)](https://github.com/mhartington/formatter.nvim/issues/73#issuecomment-889575386)

Closing, I'll take a look at `efm-langserver`.

**Comment by AllenDang** [comment]
Is this issue solved? I checked #73 , nothing useful there. Or this issue will not be solved?

**Comment by lukas-reineke** [comment]
Probably won't be solved

Use https://github.com/mattn/efm-langserver or https://github.com/jose-elias-alvarez/null-ls.nvim they both support diff formatting
