### ISSUE TITLE
Propose change to config

### ISSUE THREAD

**Issue by mhartington** [mhartington/formatter.nvim#8]
The initial setup for config was pretty adhoc, no real planning, but as the need for other keys to be added, modifying the plugin's config is going to be needed.

# Current API

```
require('format').setup({
  javascript = {
      prettier = function()
        return {
          exe = "prettier",
          args = {"--stdin-filepath", vim.api.nvim_buf_get_name(0), '--single-quote'},
          stdin = true
        }
      end
  })
```

# Proposed Change

```
require('format').setup({
  filetype = {
    javascript = {
      prettier = function() return {...} end
    }
  }
)
```

This small change would allow for adding additional keys to the setup for things like verbose logging, writing output to file, etc.

**Comment by lukas-reineke** [comment]
Makes sense :+1: 

But if we change the config anyways, we should move from `name = function` to just `function`. So users can define the order in which formatters run.
I explained that in #6 already. In lua, tables with number keys iterate in order (aka array), tables with string keys don't (aka objects)

so this will always run a before b

```
{
	function() return { exe = "a" } end,
    function() return { exe = "b" } end,
}
```

This can run either a or b first, there is no way to tell.
```
{
	a = function() return { exe = "a" } end,
    b = function() return { exe = "b" } end,
}
```

I think there will be cases where it is important in what order formatter run.

**Comment by mhartington** [comment]
This change has been made. I think preserving order is fine. We can always get feedback when a proper PR has been made 😄
