### ISSUE TITLE
Add   python formatters in config.md

### ISSUE THREAD

**Issue by shivanth** [mhartington/formatter.nvim#86]
Currently there are no formatter configuration available for python defined in https://github.com/mhartington/formatter.nvim/blob/master/CONFIG.md. It's easier if the default configuration(for any formatter)  is readily available and python bing a popular language, this is something users will be coming into check quite often.

**Comment by lukas-reineke** [comment]
Come on.. if you want something from us, at least put enough effort in to explain it properly.

Why should we do this? What formatters are you even talking about? How is their setup different from what is already in the readme?

**Comment by shivanth** [comment]
Apologies, Updated the issue desciption

**Comment by lukas-reineke** [comment]
Thank you, much better.

But I think trying to add every language and every combination of formatter to the documentation is impossible to maintain.
If a specific formatter works very different and needs special config there might be a point. But most of them, this goes for the python ones too, should work the same.
Just read the documentation of the formatter and you should be good to go.

If you get stuck somewhere, just open an issue here with the problem you are having.

**Comment by lukas-reineke** [comment]
Actually I might be wrong. I didn't know others have contributed examples configs for different formatter.
If @mhartington is fine with having these examples, than I won't complain.

**Comment by mhartington** [comment]
If there's a specific formatter that you'd like to see an example for, I'd more than happily accept a pull request for it.
I do have a note in CONFIG.md that the formatters there are a non-extensive list, and mainly serve as a source of inspiration. But a helping hand shouldn't be out of the question 😄

**Comment by maxmx03** [comment]
```
`14        python = {   
 15         -- autopep8  
 16         function()  
 17           return {  
 18             exe = "python3 -m autopep8",
 19             args = {                       
 20               "--in-place --aggressive --aggressive",  
 21               vim.fn.fnameescape(vim.api.nvim_buf_get_name(0))  
 22             },     
 23             stdin = false                                                 
 24           }                                                 
 25         end                                                 
 26       }`
```
