### ISSUE TITLE
stdin = false together with cwd = (some other dir) produces invalid tempfile path for executable

### ISSUE THREAD

**Issue by Oddegamra** [mhartington/formatter.nvim#88]
When an executable is configured in formatter.nvim with `stdin = false` and at the same time with a `cwd =` that differs from nvim's current working directory, and the current buffer was opened with a relative file path, the resulting temporary file name will also be relative, but relative to the current working directory, not to the working directory of the spawned formatter.

### Example configuration for clang-format
```
require("formatter").setup(
    {
        filetype = {
            cpp = {
                function()
                    return {
                        exe = "clang-format",
                        args = {},
                        stdin = false,
                        cwd = vim.fn.expand("%:p:h")
                    }
                end
            }
        }
    }
)
```

### Reproduction

1. `nvim subdirectory/test.cpp`
2. `:Format`

### Expected result

The file is formatted.

### Actual result

The formatter throws an error: File or directory not found. 

When the formatter is run, cwd will be `/path/to/subdirectory/`, but the temporary file passed to clang-format will be `subdirectory/~some-filename.cpp` instead of just `~some-filename.cpp`.

### Suggested solution
In [format.lua](https://github.com/mhartington/formatter.nvim/blob/c80405aca78fda2f8da586d7d087c13fdd500d85/lua/formatter/format.lua#L41), replace `local bufname = vim.fn.bufname(bufnr)` with `local bufname = api.nvim_buf_get_name(bufnr)`, which apparently always returns an absolute path of the buffer instead of a relative path. This way, the temporary file will also be created with an absolute path.

**Comment by mhartington** [comment]
Oh interesting. Thanks for the suggestion!
