### ISSUE TITLE
Buffer changed while formatting, not applying formatting

### ISSUE THREAD

**Issue by afonsocraposo** [mhartington/formatter.nvim#98]
I started using this plugin today (looks really good), but I've faced an issue when formatting on save while exiting.
I'm using the following config:
```lua
require('formatter').setup({
  filetype = {
    python = {
      function()
        return {
          exe = "black",
          args = { '-' },
          stdin = true,
        }
      end
    }
  }
})


vim.api.nvim_exec([[
augroup FormatAutogroup
  autocmd!
  autocmd BufWritePost *.py FormatWrite
augroup END
]], true)
```
Once I save and exit neovim using the command `:wq`, the following message appears as a result from it:
```
Formatter: Buffer changed while formatting, not applying formatting
```
And the saved file is not formatted.

**Comment by lukas-reineke** [comment]
`:wq` will not work.
`FormatWrite` is async. The idea is that it does not block your editor when you save, you can continue to move around and once the result of the formatter comes back, it saves the file again.
But `:wq` closes the buffer immediately after save, so once black is done formatting, the buffer is already gone.

There currently isn't a way to format synchronously.
I'm afraid your only real option for now is to not use `:wq`.
Or maybe write a custom function that listens on `FormatterPost` and closes the buffer then.

**Comment by afonsocraposo** [comment]
Thanks for the explanation!
