### ISSUE TITLE
Format VimScript with `=`

### ISSUE THREAD

**Issue by atomdmac** [mhartington/formatter.nvim#99]
Is there a way to trigger (Neo)Vim's internal `=` operator to format VimScript?  It's possible format a script manually with this but I'd like to be able to trigger it using the same `Format` and `FormatWrite` commands that I can use for my other file types.

```vimscript
ggvG=
```

**Comment by mhartington** [comment]
Very good question! Not quick sure, though my initial though is no since this plugin requires external tools to perform the formatting. Unless there's a formatting tool that does what `=` does, I'm not sure how to replicate this.

**Comment by mhartington** [comment]
No, not really. This uses `jobstart` and subprocess to run external tools. Running arbitrary nvim commands would require a refactor that is not planned for.
